[package]
name = "activity-to-routes"
version = "0.1.0"
edition = "2024"

[dependencies]
geo-types = "0.7.16"
kd-tree = "0.6.1"
polyline = "0.11.0"
priority-queue = "2.3.1"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
typenum = "1.18.0"
